 export const locationOptions = [
 { value: 'ci-abidjan,abobo', label: 'CI,Abidjan,Abobo' },
 { value: 'ci-abidjan,abobo-baoule', label: 'CI,Abidjan,Abobo-Baoulé' },
 { value: 'ci-abidjan,adjame', label: 'CI,Abidjan,Adjamé' },
 { value: 'ci-abidjan,attecoube', label: 'CI,Abidjan,Attecoubé' },
 { value: 'ci-abidjan,cocody', label: 'CI,Abidjan, Cocody' },
 { value: 'ci-abidjan,cocody-2-plateaux', label: 'CI,Abidjan,Cocody - 2 Plateaux' },
 { value: 'ci-abidjan,cocody-angre', label: 'CI,Abidjan,Cocody - Angré' },
 { value: 'ci-abidjan,koumassi', label: 'CI,Abidjan,Koumassi' },
 { value: 'ci-abidjan,koumassi-riviera', label: 'CI,Abidjan,Koumassi - Riviera' },
 { value: 'ci-abidjan,marcory', label: 'CI,Abidjan,Marcory' },
 { value: 'ci-abidjan,marcory-zone-4', label: 'CI,Abidjan,Marcory - Zone 4' },
 { value: 'ci-abidjan,plateau', label: 'CI,Abidjan,Plateau' },
 { value: 'ci-abidjan,plateau-biafra', label: 'CI,Abidjan,Plateau - Biafra' },
 { value: 'ci-abidjan,port-bouet', label: 'CI,Abidjan,Port-Bouët' },
 { value: 'ci-abidjan,port-bouet-gonzagueville', label: 'CI,Abidjan,Port-Bouët - Gonzagueville' },
 { value: 'ci-abidjan,treichville', label: 'CI,Abidjan,Treichville' },
 { value: 'ci-abidjan,yopougon', label: 'CI,Abidjan,Yopougon' },
 { value: 'ci-abidjan,yopougon-sicogi', label: 'CI,Abidjan,Yopougon - Sicogi' },
 { value: 'ci-abidjan,yopougon-andokoi', label: 'CI,Abidjan,Yopougon - Andokoi' },
 { value: 'ci-abidjan,songon', label: 'CI,Abidjan,Songon' },
 { value: 'ci-abidjan,bingerville', label: 'CI,Abidjan,Bingerville' },
 { value: 'ci-yamoussoukro', label: 'CI,Yamoussoukro' },
 { value: 'ci-bouake', label: 'CI,Bouaké' },
 { value: 'ci-daloa', label: 'CI,Daloa' },
 { value: 'ci-san-pedro', label: 'CI,San-Pédro' },
 { value: 'ci-korhogo', label: 'CI,Korhogo' },
 { value: 'ci-man', label: 'CI,Man' },
 { value: 'ci-gagnoa', label: 'CI,Gagnoa' },
 { value: 'ci-abengourou', label: 'CI,Abengourou' },
 { value: 'ci-bondoukou,quartier-zanzan', label: 'CI,Bondoukou,Zanzan' },
 { value: 'ci-segela', label: 'CI,Séguéla' },
 { value: 'ci-odienne', label: 'CI,Odienné' },
 { value: 'ci-ferkessedougou', label: 'CI,Ferkessédougou' },
 { value: 'ci-issia', label: 'CI,Issia' },
 { value: 'ci-dabou', label: 'CI,Dabou' },
 // Ajoutez d'autres options selon vos besoins
]
